name: Docker

on:
  push:
    branches: ["main"]

jobs:
  # Deploy to both docker.io
  dockerhub:
    runs-on: ubuntu-20.04

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Load the rust toolchain
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      # Load any cache stored by rust-cache
      - uses: Swatinem/rust-cache@v1

      # Run cargo check (for release)
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          args: "--release"
          command: check

      # Run cargo build (for release)
      - uses: actions-rs/cargo@v1
        with:
          args: "--release"
          command: build

      # Run cargo test (for release)
      - uses: actions-rs/cargo@v1
        with:
          args: "--release"
          command: test

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build the image
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: chksm/magnesium-oxide:latest
