name: Build

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  release:
    strategy:
      matrix:
        include:
          - target: windows-latest
            type: ".exe"
          - target: ubuntu-latest
            type: ""
          - target: macos-latest
            type: ""

    runs-on: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Get Mercury version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build Mercury"
        run: |
          cargo build

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: mercury-oxide (${{ matrix.target }})
          path: target/debug/mercury-oxide${{ matrix.type }}