name: Build Prod

on:
  push:
    branches: [stable]
  pull_request:
    branches: [stable]

jobs:
  release:
    strategy:
      matrix:
        include:
          - target: ubuntu-latest

    runs-on: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: "Build Magnesium"
        run: |
          cargo build --release

      - name: "Install SSH Key"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "space"

      - name: "Set known_hosts"
        run: |
          ssh-keyscan -H ${{ secrets.SSH_KNOWN_HOSTS }} >> ~/.ssh/known_hosts

      - run: cd /srv/magnesium-oxide && sudo systemctl stop magnesium-oxide

      - name: "Deploy with RSync"
        run: |
          rsync -avz target/debug/magnesium-oxide ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/magnesium-oxide/

      - run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /srv/magnesium-oxide && systemctl start magnesium-oxide"

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: magnesium-oxide (${{ matrix.target }})
          path: target/debug/magnesium-oxide