name: Build Prod

on:
  push:
    branches: [stable]
  pull_request:
    branches: [stable]

jobs:
  release:
    strategy:
      matrix:
        include:
          - target: ubuntu-latest

    runs-on: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: "Build Magnesium"
        run: |
          cargo build --release

      - name: "Install SSH Key"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "space"

      - name: "Set known_hosts"
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: "Stop Magnesium"
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo ${{ secrets.SSH_PASSWORD }} | sudo --stdin -- bash -c 'systemctl stop magnesium'"

      - name: "Deploy Magnesium"
        run: |
          scp target/debug/magnesium-oxide ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/magnesium-oxide/

      - name: "Start Magnesium"
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo ${{ secrets.SSH_PASSWORD }} | sudo --stdin -- bash -c 'systemctl start magnesium'"

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: magnesium-oxide (${{ matrix.target }})
          path: target/debug/magnesium-oxide