name: Build Mercury

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    strategy:
      matrix:
        include:
          - target: windows-latest
            type: ".exe"
          - target: ubuntu-latest
            type: ""
          - target: macos-latest
            type: ""

    runs-on: ${{ matrix.target }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Cache"
        uses: Swatinem/rust-cache@v1

      - name: Get Mercury version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: "Build Mercury"
        run: cargo build --target-dir ${{ matrix.target }} --verbose

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: ${{ matrix.target }}/debug/hello_world${{ matrix.type }}

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}